Repository Duri-Salon/Duri-BE, pull requests merged in 2024-12, with the labels that each got.

#22 [Feat] 보낸 견적서 상세 조회 API(DURI-316)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/QuotationDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/QuotationShopDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/QuotationFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/QuotationMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/QuotationController.java
  app/src/main/java/kr/com/duri/groomer/repository/GroomerRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/ApprovedQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/NewQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/PetDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
Labels: ✨ Feature, 🐙 김태연

#23 [Feat] 고객 리뷰 관련 CRUD API (DURI-286)
  .github/workflows/duri_ci_cd.yml
  app/build.gradle
  app/src/main/java/kr/com/duri/client/external/MultipartJackson2HttpMessageConverter.java
  app/src/main/java/kr/com/duri/client/external/S3Config.java
  app/src/main/java/kr/com/duri/common/CommonControllerAdvice.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Groomer.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
  app/src/main/java/kr/com/duri/user/application/dto/request/NewReviewRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/request/UpdateReviewRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/response/ReviewResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/ReviewMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewImageService.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewImageServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewService.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Review.java
  app/src/main/java/kr/com/duri/user/domain/entity/ReviewImage.java
  app/src/main/java/kr/com/duri/user/exception/PetNotFoundException.java
  app/src/main/java/kr/com/duri/user/exception/ReviewImageUploadException.java
  app/src/main/java/kr/com/duri/user/exception/ReviewNotFoundException.java
  app/src/main/java/kr/com/duri/user/repository/PetRepository.java
  app/src/main/java/kr/com/duri/user/repository/ReviewImageRepository.java
  app/src/main/java/kr/com/duri/user/repository/ReviewRepository.java
  build.gradle
Labels: 🐞 BugFix, ✨ Feature, 🐳 김은수

#24 [Feat] 견적 요청서 작성 및 요청(DURI-211)
  app/src/main/java/kr/com/duri/common/CommonControllerAdvice.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/request/NewQuotationReqRequest.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/RequestService.java
  app/src/main/java/kr/com/duri/user/application/service/RequestServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/QuotationReqController.java
  app/src/main/java/kr/com/duri/user/domain/entity/QuotationReq.java
  app/src/main/java/kr/com/duri/user/repository/QuotationReqRepository.java
  app/src/main/java/kr/com/duri/user/repository/RequestRepository.java
Labels: ✨ Feature, 🐙 김태연

#25 [Feat] 태그 테이블, 매장 별점, 견적서 시술여부 추가 (DURI-26)
  app/src/main/java/kr/com/duri/groomer/domain/entity/Quotation.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/ShopTag.java
Labels: ✨ Feature, 🐳 김은수

#26 [Feat] 소셜 로그인 API (DURI-226, DURI-238)
  app/build.gradle
  app/src/main/java/kr/com/duri/common/security/config/CorsMvcConfig.java
  app/src/main/java/kr/com/duri/common/security/config/SecurityConfig.java
  app/src/main/java/kr/com/duri/common/security/dto/NaverUserDto.java
  app/src/main/java/kr/com/duri/common/security/dto/ShopUserDto.java
  app/src/main/java/kr/com/duri/common/security/dto/SiteUserDto.java
  app/src/main/java/kr/com/duri/common/security/jwt/JwtFilter.java
  app/src/main/java/kr/com/duri/common/security/jwt/JwtUtil.java
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomOAuth2UserService.java
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomSuccessHandler.java
  app/src/main/java/kr/com/duri/common/security/provider/NaverOAuth2User.java
  app/src/main/java/kr/com/duri/common/security/provider/NaverShopResponse.java
  app/src/main/java/kr/com/duri/common/security/provider/NaverUserResponse.java
  app/src/main/java/kr/com/duri/common/security/provider/OAuth2Response.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserService.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserServiceImpl.java
  app/src/main/java/kr/com/duri/user/domain/Enum/Gender.java
  app/src/main/java/kr/com/duri/user/domain/entity/SiteUser.java
  app/src/main/java/kr/com/duri/user/repository/SiteUserRepository.java
  build.gradle
Labels: ✨ Feature, 🦭 김재승

#27 [Refactor]: QuotationReqService 코드 분리
  app/src/main/java/kr/com/duri/groomer/application/facade/QuotationFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/RequestService.java
  app/src/main/java/kr/com/duri/user/application/service/RequestServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewServiceImpl.java
Labels: ♻️ Refactor, 🐙 김태연

#28 [Fix] Cors Config 수정 (-)
  app/src/main/java/kr/com/duri/common/security/config/CorsMvcConfig.java
Labels: 🐞 BugFix, ⚙️ Setting, 🦭 김재승

#30 [Fix] 모든 메소드 요청 허용 (-)
  app/src/main/java/kr/com/duri/common/security/config/SecurityConfig.java
Labels: 🐞 BugFix, ⚙️ Setting, 🦭 김재승

#31 [Feat] 주변 미용실 조회 API(DURI-208)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopNearByResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopTagService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopTagServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Quotation.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopTagRepository.java
Labels: ✨ Feature, 🐙 김태연

#32 [Feat] 미용실 홈화면 API (DURI-220)
  app/src/main/java/kr/com/duri/common/CommonControllerAdvice.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/QuotationUpdateCompleteRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/RecentProcedureResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/TodayScheduleResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerHomeFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerHomeMapper.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerHomeController.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Quotation.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/ShopImage.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/mapper/ReviewMapper.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/domain/entity/Request.java
  app/src/main/java/kr/com/duri/user/exception/QuotationReqNotFoundException.java
Labels: ✨ Feature, ♻️ Refactor, 🐳 김은수

#33 [Feat]주변 미용실 거리순/평점순 조회 API(DURI-209)
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
Labels: ✨ Feature, 🐙 김태연

#34 [Feat] 이번달 매장 총 매출액 조회 (DURI-322)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/MonthIncomeResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerHomeFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerHomeController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/user/application/service/PaymentService.java
  app/src/main/java/kr/com/duri/user/application/service/PaymentServiceImpl.java
  app/src/main/java/kr/com/duri/user/domain/entity/Payment.java
  app/src/main/java/kr/com/duri/user/repository/PaymentRepository.java
Labels: ✨ Feature, 🐳 김은수

#36 [Feat] 미용사 홈 - 받은 견적서 요청서 목록 조회(DURI-325)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/HomeQuotationReqResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerHomeFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerHomeMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerHomeController.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/repository/RequestRepository.java
Labels: ✨ Feature, 🐳 김은수

#38 [Refactor] QuotationFacade 주입 수정
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/PetServiceImpl.java
Labels: ♻️ Refactor, 🐙 김태연

#39 [Feat] 토스 결제 API 구현(DURI-218)
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/dto/request/ConfirmPaymentRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/request/SaveAmountRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/response/PaymentResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/PaymentFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/PaymentMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PaymentService.java
  app/src/main/java/kr/com/duri/user/application/service/PaymentServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/PaymentController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Payment.java
  build.gradle
Labels: ✨ Feature, 🐙 김태연

#40 [Feat] 매장 리뷰 간단/상세 리스트 조회 (DURI-294)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopReviewDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopReviewResponse.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/user/application/dto/request/NewReviewRequest.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/ReviewMapper.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewImageServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewService.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Review.java
  app/src/main/java/kr/com/duri/user/repository/ReviewRepository.java
Labels: ✨ Feature, ♻️ Refactor, 🐳 김은수

#41 [Feat] 고객, 매장 토큰 발급 API (DURI-226, DURI-238)
  app/src/main/java/kr/com/duri/common/security/config/CorsMvcConfig.java
  app/src/main/java/kr/com/duri/common/security/config/SecurityConfig.java
  app/src/main/java/kr/com/duri/common/security/jwt/JwtUtil.java
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomSuccessHandler.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/NewShopJwtResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopAuthFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopJwtMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopAuthController.java
  app/src/main/java/kr/com/duri/user/application/dto/response/NewUserJwtResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserAuthFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserJwtMapper.java
  app/src/main/java/kr/com/duri/user/controller/UserAuthController.java
Labels: ✨ Feature, ♻️ Refactor, 🦭 김재승

#42 [Refactor] 사용자 토큰 발급 일부 리팩토링 (DURI-226, DURI-238)
  README.md
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopAuthFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopJwtMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/GroomerServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopTagServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/facade/UserAuthFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserJwtMapper.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PaymentServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RequestServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/ReviewImageServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/ReviewServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/SiteUserServiceImpl.java
Labels: ♻️ Refactor, 🦭 김재승, 👀 ETC

#43 [Fix]견적 요청서 상세 정보 응답 정보 수정(DURI-228)
  app/src/main/java/kr/com/duri/user/application/dto/response/MenuDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/NewQuotationReqDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
Labels: ♻️ Refactor, 🐙 김태연

#44 [Fix]결제 후 Quotation상태 변화 변경(DURI-218)
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Quotation.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/facade/PaymentFacade.java
  app/src/main/java/kr/com/duri/user/domain/entity/Payment.java
Labels: ♻️ Refactor, 🐙 김태연

#45 [Feat] 매장 검색 API구현(DURI-272)
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
Labels: ✨ Feature, 🐙 김태연

#47 [Feat] 고객 온보딩 API 구현 (DURI-258)
  app/src/main/java/kr/com/duri/common/security/jwt/JwtFilter.java
  app/src/main/java/kr/com/duri/common/security/jwt/JwtUtil.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/HomeQuotationReqResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/RecentProcedureResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/TodayScheduleResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/request/NewPetRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/response/PetDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/PetMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/SiteUserServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Pet.java
  app/src/main/java/kr/com/duri/user/exception/UserNotFoundException.java
Labels: ✨ Feature, 🦭 김재승

#46 [Feat] 고객 홈 - 다음 예약 내역 조회 (DURI-275)
  app/src/main/java/kr/com/duri/common/CommonControllerAdvice.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerHomeFacade.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/RecentProcedureResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Pet.java
Labels: ✨ Feature, 🐳 김은수

#48 [Fix] 답장한 견적 요청서 리스트 조회 응답 수정
  app/src/main/java/kr/com/duri/user/application/dto/response/ApprovedQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
Labels: ♻️ Refactor, 🐙 김태연

#49 [Feat] 고객 홈 - 단골샵 조회 API (DURI-217)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/TodayScheduleResponse.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerHomeMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/HomeShopResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/RegularShopResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
Labels: ✨ Feature, ♻️ Refactor, 🐳 김은수

#50 [Feat]예약확정/시술완료 견적요청서 리스트 조회(DURI-232)
  app/src/main/java/kr/com/duri/user/application/dto/response/ReservationQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/application/service/RequestService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RequestServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/QuotationReqController.java
  app/src/main/java/kr/com/duri/user/repository/RequestRepository.java
Labels: ✨ Feature, 🐙 김태연

#51 [Fix]주변 미용실 조회 리스트 수정(DURI-208)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopNearByResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
Labels: ♻️ Refactor, 🐙 김태연

#52 [Feat] 고객 마이페이지 - 이용 기록 조회 API (DURI-329)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/RecentProcedureResponse.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerHomeMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/HistoryResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/HomePetInfoResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/MonthlyHistoryResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserInfoMapper.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
  app/src/main/java/kr/com/duri/user/domain/Enum/Day.java
Labels: ✨ Feature, 🐳 김은수

#55 [Feat] 고객 홈 - 매장 추천 API 추가 (DURI-221)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/RecentProcedureResponse.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/RecommendShopResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/PetMapper.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
Labels: ✨ Feature, ♻️ Refactor, 🐳 김은수

#56 [Feat] 견적 요청서 목록(DURI-332)
  app/src/main/java/kr/com/duri/user/application/dto/response/QuotationListResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/QuotationListShopResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/RequestService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RequestServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/QuotationReqController.java
  app/src/main/java/kr/com/duri/user/repository/QuotationReqRepository.java
  app/src/main/java/kr/com/duri/user/repository/RequestRepository.java
Labels: ✨ Feature, 🐙 김태연

#57 [Feat] 매장 온보딩 로직 추가 (DURI-260)
  app/src/main/java/kr/com/duri/common/Mapper/CommonMapper.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/GroomerDetailRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/GroomerOnboardingInfo.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/ShopDetailRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/ShopOnboardingInfo.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/ShopOnboardingRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/NewShopJwtResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopOnboardingResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopOnboardingFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerMapper.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopJwtMapper.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/GroomerService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/GroomerServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopOnboardingController.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/Gender.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Groomer.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
Labels: ✨ Feature, ♻️ Refactor, 🦭 김재승

#58 [Refactor] userId와 shopId - 헤더에서 꺼내올 수 있도록 전체 코드 수정 (DURI-ETC)
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerHomeFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerHomeController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
Labels: ♻️ Refactor, 🐳 김은수

#59 [Feat]견적 요청서 + 견적 현황 조회(DURI-213)
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/request/QuotationReqDetailRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/response/QuotationReqDetailRequestListResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/QuotationReqDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/ShopBestResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/controller/QuotationReqController.java
Labels: ✨ Feature, 🐙 김태연

#60 [Feat] 미용사 프로필 CRUD API (DURI-261, DURI-263, DURI-264)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/GroomerProfileDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerProfileFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/GroomerService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/GroomerServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerProfileController.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Groomer.java
Labels: ✨ Feature, 🦭 김재승

#61 [Feat] 지난 견적 요청서 조회(DURI-214)
  app/src/main/java/kr/com/duri/user/application/dto/response/LastMenuDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/LastQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/QuotationReqController.java
  app/src/main/java/kr/com/duri/user/repository/QuotationReqRepository.java
Labels: ✨ Feature, 🐙 김태연

#62 [Feat] 애견 프로필 CRU API (DURI-258, DURI-250, DURI-253)
  app/src/main/java/kr/com/duri/common/s3/S3Util.java
  app/src/main/java/kr/com/duri/user/application/dto/response/PetProfileListResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/PetProfileResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/PetMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Pet.java
Labels: ✨ Feature, 🦭 김재승

#63 [Refactor] 견적서 상세 보기 견적 상태 추가
  app/src/main/java/kr/com/duri/groomer/application/dto/response/QuotationDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/QuotationFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/QuotationMapper.java
  app/src/main/java/kr/com/duri/user/application/dto/request/NewQuotationReqRequest.java
  app/src/main/java/kr/com/duri/user/application/dto/response/LastMenuDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/MenuDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PaymentService.java
  app/src/main/java/kr/com/duri/user/application/service/ReviewService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PaymentServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/ReviewServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/QuotationReqController.java
  app/src/main/java/kr/com/duri/user/repository/PaymentRepository.java
  app/src/main/java/kr/com/duri/user/repository/ReviewRepository.java
Labels: ♻️ Refactor, 🐙 김태연

#64 [Feat] 매장 이미지 단일, 리스트 조회 로직 (-)
  app/src/main/java/kr/com/duri/groomer/application/service/ShopImageService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopImageServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/ImageCategory.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/ShopImage.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopImageRepository.java
Labels: ✨ Feature, 🦭 김재승

#65 [Refactor] 컨트롤러 리팩토링 (-)
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopAuthFacade.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerProfileController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopAuthController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopOnboardingController.java
  app/src/main/java/kr/com/duri/user/application/facade/UserAuthFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/SiteUserServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserAuthController.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
  app/src/main/java/kr/com/duri/user/domain/entity/SiteUser.java
Labels: 🐞 BugFix, ♻️ Refactor, 🦭 김재승

#66 [Feat] 고객 프로필 조회, 수정 API 개발 (DURI-246, DURI-256)
  app/src/main/java/kr/com/duri/common/CommonControllerAdvice.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Quotation.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/SiteUserProfileResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserInfoMapper.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/SiteUserServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Pet.java
  app/src/main/java/kr/com/duri/user/domain/entity/SiteUser.java
Labels: ✨ Feature, ♻️ Refactor, 🦭 김재승

#67 [Feat] 고객 홈 - 반려견 AI 스타일링 API (DURI-281)
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/service/AiService.java
  app/src/main/java/kr/com/duri/user/application/service/RecommendService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/AiServiceimpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RecommendServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
  build.gradle
Labels: ✨ Feature, ♻️ Refactor, 🐳 김은수

#68 [Chore] 프론트 배포 환경과 통합 테스트 (-)
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomSuccessHandler.java
Labels: 🦭 김재승, 👀 ETC

#69 [Refactor] 견적 관련 백엔드 리팩토링
  app/src/main/java/kr/com/duri/groomer/application/facade/QuotationFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerHomeMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Quotation.java
  app/src/main/java/kr/com/duri/user/application/dto/response/ApprovedQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/NewQuotationReqResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserInfoMapper.java
Labels: ♻️ Refactor, 🐙 김태연

#70 [Feat] 월별, 일별, 선택한 월 매출액 통계 API (DURI-291)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/FiveMonthIncomeResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/IncomeResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/SelectMonthIncomeResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/WeekIncomeResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/StastisticsFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/StatisticsMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/groomer/controller/StatisticsController.java
  app/src/main/java/kr/com/duri/user/application/dto/response/HomePetInfoResponse.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/application/service/PaymentService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PaymentServiceImpl.java
  app/src/main/java/kr/com/duri/user/repository/PaymentRepository.java
Labels: ✨ Feature, ♻️ Refactor, 🐳 김은수

#71 feat: 미용실 상세 정보 조회(DURI-210)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/GetShopDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/user/application/dto/response/GetShopReviewDetailResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/ReviewMapper.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
Labels: ✨ Feature, 🐙 김태연

#72 [Feat] 매장 마이페이지 API 개발 (DURI-262)
  app/src/main/java/kr/com/duri/groomer/application/dto/request/ShopProfileDetailRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopOnboardingResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopProfileDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopOnboardingFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopProfileFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerMapper.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/GroomerService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopImageService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/GroomerServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopImageServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopOnboardingController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopProfileController.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/ShopImage.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopImageRepository.java
Labels: ✨ Feature, 🦭 김재승

#73 [Feat] 반려견 나이별, 질환별, 성격별, 키워드별 통계 조회(DURI-349)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/AgeStatisticsResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/BestStatisticsResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/CharacterStatisticsResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/DiseaseStatisticsResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/StatisticsResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/StatisticsFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/StatisticsMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/StatisticsService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/StatisticsServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/StatisticsController.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/dto/response/HomePetInfoResponse.java
Labels: ✨ Feature, 🐳 김은수

#74 [Refactor] Review 관련 API 화면에 맞게 수정 (DURI-288)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopReviewResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/StatisticsFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/StatisticsMapper.java
  app/src/main/java/kr/com/duri/groomer/controller/StatisticsController.java
  app/src/main/java/kr/com/duri/user/application/dto/response/QuotationPetReviewResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/ReviewResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/ShopInfoResponse.java
  app/src/main/java/kr/com/duri/user/application/dto/response/UserReviewResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/ReviewMapper.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
Labels: ♻️ Refactor, 🐳 김은수

#75 [Chore] Duri-Salon_BE_v.1.0.1 (-)
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomSuccessHandler.java
Labels: 🦭 김재승, 👀 ETC

#77 [Refactor]견적 요청 작성 24시간 이후 자동 만료
  app/src/main/java/kr/com/duri/MainApplication.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqScheduler.java
  app/src/main/java/kr/com/duri/user/application/service/QuotationReqService.java
  app/src/main/java/kr/com/duri/user/application/service/RequestService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/QuotationReqServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RequestServiceImpl.java
  app/src/main/java/kr/com/duri/user/domain/entity/QuotationReq.java
  app/src/main/java/kr/com/duri/user/domain/entity/Request.java
  app/src/main/java/kr/com/duri/user/repository/QuotationReqRepository.java
  app/src/main/java/kr/com/duri/user/repository/RequestRepository.java
Labels: ♻️ Refactor, 🐙 김태연

#79 [Chore] Duri-Salon_BE_v.1.0.1 (local)
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomSuccessHandler.java
Labels: 🦭 김재승, 👀 ETC

#80 [Refactor] 펫 정보 조회 수정
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqScheduler.java
Labels: ♻️ Refactor, 🐙 김태연

#83 [Feat] swaggerConfig 추가 (-)
  app/src/main/java/kr/com/duri/common/swagger/SwaggerConfig.java
  build.gradle
Labels: ✨ Feature, 🦭 김재승, 👀 ETC

#81 [Refactor] 프론트엔드 수정 요청 처리
  app/src/main/java/kr/com/duri/user/application/dto/response/QuotationListResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqScheduler.java
  app/src/main/java/kr/com/duri/user/application/mapper/QuotationReqMapper.java
Labels: 🐞 BugFix, ♻️ Refactor, 🐙 김태연

#84 [Refactor] 미용사 - 매장 이미지 조회 연결 및 CORS 에러 해결 (DURI-220)
  app/src/main/java/kr/com/duri/common/security/config/CorsMvcConfig.java
  app/src/main/java/kr/com/duri/common/security/config/SecurityConfig.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerHomeFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/GroomerHomeMapper.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
Labels: 🐞 BugFix, ♻️ Refactor, 🐳 김은수

#85 [Feat] Payment Key 발급
  app/src/main/java/kr/com/duri/user/application/dto/response/GenerateKeyResponse.java
  app/src/main/java/kr/com/duri/user/controller/PaymentController.java
Labels: ✨ Feature, 🐙 김태연

#86 [Feat] 피드백 관련 API 개발 (DURI-296)
  app/src/main/java/kr/com/duri/groomer/application/dto/request/NewFeedbackRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/DiaryDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/FeedbackDataResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/FeedbackDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/PortfolioDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/PortfolioListResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/FeedbackFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/FeedbackMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/FeedbackImageService.java
  app/src/main/java/kr/com/duri/groomer/application/service/FeedbackService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/FeedbackImageServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/FeedbackServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/FeedbackController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopProfileController.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/Behavior.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/Friendly.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/Matter.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/Reaction.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Feedback.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/FeedbackImage.java
  app/src/main/java/kr/com/duri/groomer/repository/FeedbackImageRepository.java
  app/src/main/java/kr/com/duri/groomer/repository/FeedbackReopsitory.java
Labels: ✨ Feature, 🦭 김재승

#87 [Refactor] 미용사 프로필 관련 API 리팩토링 (DURI-260)
  app/src/main/java/kr/com/duri/groomer/application/dto/request/GroomerDetailRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/GroomerOnboardingInfo.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerProfileFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopProfileFacade.java
  app/src/main/java/kr/com/duri/groomer/application/service/GroomerService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/GroomerServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerProfileController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopProfileController.java
Labels: ♻️ Refactor, 🦭 김재승

#88 [Refactor] 최신 빌드 수정 (-)
  app/src/main/java/kr/com/duri/common/security/config/SecurityConfig.java
  app/src/main/java/kr/com/duri/groomer/application/dto/request/NewFeedbackRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/DiaryDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/FeedbackDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/PortfolioDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/FeedbackFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/FeedbackMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/FeedbackService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/FeedbackServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/FeedbackController.java
  app/src/main/java/kr/com/duri/groomer/domain/Enum/Matter.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Feedback.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/repository/PetRepository.java
Labels: 🦭 김재승, 👀 ETC

#91 [Refactor] 포트폴리오 관련 API 일부 수정 (DURI-296)
  app/src/main/java/kr/com/duri/groomer/application/dto/request/PortfolioUpdateRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/GroomerInfoResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/PetInfoResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/PortfolioDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/FeedbackFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/FeedbackMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/FeedbackService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/FeedbackServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/FeedbackController.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Feedback.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/repository/PetRepository.java
Labels: ✨ Feature, ♻️ Refactor, 🦭 김재승

#92 [Refactor] 서킷브레이커, timeout 설정
  app/src/main/java/kr/com/duri/user/application/dto/request/SaveAmountRequest.java
  app/src/main/java/kr/com/duri/user/application/facade/PaymentFacade.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PaymentServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/PaymentController.java
  build.gradle
Labels: ♻️ Refactor, 🐙 김태연

#93 [Refactor] 고객 홈 화면 - 가격 정상 추출 (DURI-275)
  app/src/main/java/kr/com/duri/user/application/dto/response/RecentProcedureResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
Labels: ♻️ Refactor, 🐳 김은수

#94 [Refactor] 견적서 상세 조회 이미지 추가
  app/src/main/java/kr/com/duri/groomer/application/dto/request/QuotationRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/QuotationDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/QuotationShopDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/QuotationFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/QuotationMapper.java
Labels: ♻️ Refactor, 🐙 김태연

#95 [Refactor] 프로필 조회 관련 API 수정 (-)
  app/src/main/java/kr/com/duri/groomer/application/dto/request/ShopProfileDetailRequest.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/GroomerAndShopProfileRespnse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/GroomerMyPageResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopProfileDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/GroomerProfileFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopFacade.java
  app/src/main/java/kr/com/duri/groomer/application/facade/ShopProfileFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/QuotationService.java
  app/src/main/java/kr/com/duri/groomer/application/service/ShopTagService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/QuotationServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopTagServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/controller/GroomerProfileController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopController.java
  app/src/main/java/kr/com/duri/groomer/controller/ShopProfileController.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/Shop.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/ShopTag.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopTagRepository.java
  app/src/main/java/kr/com/duri/user/application/service/RequestService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RequestServiceImpl.java
Labels: ✨ Feature, ♻️ Refactor, 🦭 김재승

#96 [Refactor] 고객 히스토리 - 요청(Request) 추가, 매장 추천 변경 (DURI-331)
  app/src/main/java/kr/com/duri/user/application/dto/response/HistoryResponse.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserInfoMapper.java
  app/src/main/java/kr/com/duri/user/application/service/impl/RecommendServiceImpl.java
Labels: ♻️ Refactor, 🐳 김은수

#98 [Refactor] 이용기록 - Approved 추가 (DURI-331)
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserInfoMapper.java
Labels: ♻️ Refactor, 🐳 김은수

#99 [Refactor] 견적서 complete default 설정
  app/src/main/java/kr/com/duri/groomer/application/mapper/QuotationMapper.java
Labels: ♻️ Refactor, 🐙 김태연

#100 [Refactor] 매장 조회 관련 수정 (-)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopProfileDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/domain/entity/ShopImage.java
  app/src/main/java/kr/com/duri/user/application/facade/ReviewFacade.java
  app/src/main/java/kr/com/duri/user/controller/ReviewController.java
Labels: ♻️ Refactor, 🦭 김재승

#101 [Refactor] 일지 Response 보충 (-)
  app/src/main/java/kr/com/duri/groomer/application/dto/response/DiaryDetailResponse.java
  app/src/main/java/kr/com/duri/groomer/application/facade/FeedbackFacade.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/FeedbackMapper.java
Labels: ♻️ Refactor, 🦭 김재승

#102 [Refactor] 통합 테스트 및 최종 리팩토링 (-)
  app/src/main/java/kr/com/duri/common/security/config/CorsMvcConfig.java
  app/src/main/java/kr/com/duri/common/security/config/SecurityConfig.java
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomOAuth2UserService.java
  app/src/main/java/kr/com/duri/common/security/provider/NaverUserResponse.java
  app/src/main/java/kr/com/duri/groomer/application/dto/response/ShopNearByResponse.java
  app/src/main/java/kr/com/duri/groomer/application/mapper/ShopMapper.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
  app/src/main/java/kr/com/duri/user/application/facade/QuotationReqFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/facade/UserInfoFacade.java
  app/src/main/java/kr/com/duri/user/application/service/PetService.java
  app/src/main/java/kr/com/duri/user/application/service/SiteUserService.java
  app/src/main/java/kr/com/duri/user/application/service/impl/PetServiceImpl.java
  app/src/main/java/kr/com/duri/user/application/service/impl/SiteUserServiceImpl.java
  app/src/main/java/kr/com/duri/user/controller/UserInfoController.java
  app/src/main/java/kr/com/duri/user/domain/entity/Pet.java
  app/src/main/java/kr/com/duri/user/domain/entity/SiteUser.java
  app/src/main/java/kr/com/duri/user/repository/PetRepository.java
Labels: ✨ Feature, ♻️ Refactor, 🦭 김재승

#103 [Refactor] 미용사 통계 - 내림차순 정렬 및 승인 조건 추가 (DURI-331)
  app/src/main/java/kr/com/duri/groomer/application/facade/StatisticsFacade.java
  app/src/main/java/kr/com/duri/groomer/repository/QuotationRepository.java
Labels: ♻️ Refactor, 🐳 김은수

#104 [Chore] 리다이렉트 url 수정 (도메인, 메인) (-)
  app/src/main/java/kr/com/duri/common/security/oauth2/CustomSuccessHandler.java
Labels: 🦭 김재승, 👀 ETC

#105 [Feat] 고객 홈 - 비회원을 위한 매장 거리순 목록 제공 (DURI-208)
  app/src/main/java/kr/com/duri/groomer/application/service/ShopService.java
  app/src/main/java/kr/com/duri/groomer/application/service/impl/ShopServiceImpl.java
  app/src/main/java/kr/com/duri/groomer/repository/ShopRepository.java
  app/src/main/java/kr/com/duri/user/application/facade/UserHomeFacade.java
  app/src/main/java/kr/com/duri/user/application/mapper/UserHomeMapper.java
  app/src/main/java/kr/com/duri/user/controller/UserHomeController.java
Labels: ♻️ Refactor, 🐳 김은수
